name: test

on:
  pull_request:
  push:
    branches:
    - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Use node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install
      run: npm install
    - name: Test
      run: npm run test
